# Copyright 2026 The Zilkworm Authors
# SPDX-License-Identifier: Apache-2.0

[package]
version = "0.1.0"
name = "z6m_guest_turbo"
edition = "2021"


[dependencies]
cxx = "1.0.160"                 # runtime bridge

[dependencies.libm]
version = "0.2.15"
default-features = false

[dependencies.sp1-zkvm]
version = "5.2.2"
default-features = false
features = ["embedded", "lib"]

[dependencies.bls12_381]
version = "=0.8.0-sp1-5.0.0"
#TODO: We don't need the "alloc" feature but it doesn't compile without it.
features = ["groups", "pairings", "alloc"]
default-features = false
package = "sp1_bls12_381"

[build-dependencies]
cmake = "0.1.54"
cxx-build = "1.0.160"           # build-time codegen & C++ compilation
cc = "1.2.29"
pkg-config = "0.3"
