# Copyright 2026 The Zilkworm Authors
# SPDX-License-Identifier: Apache-2.0

[package]
version = "0.1.0"
name = "z6m_prover"
edition = "2021"
default-run = "z6m_prover"

[[bin]]
name = "z6m_prover"
path = "src/main.rs"

[dependencies]
sp1-sdk = { git = "https://github.com/erigontech/sp1.git", branch = "erigon/patches-v6.0.2", features = ["profiling"] }
sp1-prover = { git = "https://github.com/erigontech/sp1.git", branch = "erigon/patches-v6.0.2" }
sp1-cuda = { git = "https://github.com/erigontech/sp1.git", branch = "erigon/patches-v6.0.2" }
sp1-core-executor = { git = "https://github.com/erigontech/sp1.git", branch = "erigon/patches-v6.0.2" }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
serde = { version = "1.0.200", default-features = false, features = ["derive"] }
clap = { version = "4.0", features = ["derive", "env"] }
bincode = { version = "2.0.1", features = ["serde"] }
tracing = "0.1.40"
hex = "0.4.3"
alloy-sol-types = { workspace = true }
dotenv = "0.15.0"
cxx = "1.0.160"                                                                  # runtime bridge
# alloy-primitives = "1.3.1"
# alloy-rlp = "0.3.12"
# alloy-rpc-types-debug = "1.0.35"
# alloy-consensus = "1.0.35"

alloy = { version = "1.0", features = [
    "full",
    "node-bindings",
    "rpc-types-debug",
] }
alloy-provider = "1.0"
alloy-primitives = "1.0"
alloy-consensus = "1.0"
alloy-network = "1.0"
alloy-rpc-types = "1.0"
alloy-rpc-types-debug = "1.0"
alloy-rlp = "0.3"
alloy-eips = "1.0"
alloy-transport = "1.0"
alloy-transport-http = "1.0"
reqwest = { version = "0.12", features = ["json"] }
eyre = "0.6"
# serde = { version = "1.0", features = ["derive"] }
# serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
url = "2.5"
futures = "0.3"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
base64 = "0.22"
chrono = { version = "0.4", features = ["serde"] }
z6m_common = { path = "../common" }


[dependencies.libm]
version = "0.2.15"
default-features = false

[dependencies.sp1-zkvm]
git = "https://github.com/erigontech/sp1.git"
branch = "erigon/patches-v6.0.2"
default-features = false

[build-dependencies]
sp1-build = { git = "https://github.com/erigontech/sp1.git", branch = "erigon/patches-v6.0.2" }
cxx-build = "1.0.160" # build-time codegen & C++ compilation
