// Copyright 2026 The Zilkworm Authors (modifications)
// Copyright 2025 The Original Silkworm Authors
// SPDX-License-Identifier: Apache-2.0

#pragma once

#include <zilk_core/core/chain/config.hpp>
#include <zilk_core/core/types/block.hpp>
#include <zilk_core/core/types/receipt.hpp>
#include <zilk_core/core/types/transaction.hpp>

namespace silkworm::test {

//! Always Frontier rules.
inline constexpr ChainConfig kFrontierConfig{
    .chain_id = 1,
    .rule_set_config = protocol::EthashConfig{.validate_seal = false},
};

//! Enables London from genesis.
inline constexpr ChainConfig kLondonConfig{
    .chain_id = 1,
    .homestead_block = 0,
    .tangerine_whistle_block = 0,
    .spurious_dragon_block = 0,
    .byzantium_block = 0,
    .constantinople_block = 0,
    .petersburg_block = 0,
    .istanbul_block = 0,
    .berlin_block = 0,
    .london_block = 0,
    .rule_set_config = protocol::EthashConfig{.validate_seal = false},
};

//! Enables Shanghai from genesis.
inline constexpr ChainConfig kShanghaiConfig{
    .chain_id = 1,
    .homestead_block = 0,
    .tangerine_whistle_block = 0,
    .spurious_dragon_block = 0,
    .byzantium_block = 0,
    .constantinople_block = 0,
    .petersburg_block = 0,
    .istanbul_block = 0,
    .berlin_block = 0,
    .london_block = 0,
    .terminal_total_difficulty = 0,
    .shanghai_time = 0,
};

//! Enables Prague from genesis.
inline constexpr ChainConfig kPragueConfig{
    .chain_id = 1,
    .homestead_block = 0,
    .tangerine_whistle_block = 0,
    .spurious_dragon_block = 0,
    .byzantium_block = 0,
    .constantinople_block = 0,
    .petersburg_block = 0,
    .istanbul_block = 0,
    .berlin_block = 0,
    .london_block = 0,
    .terminal_total_difficulty = 0,
    .shanghai_time = 0,
    .cancun_time = 0,
    .prague_time = 0,
};

inline const std::map<std::string, ChainConfig> kNetworkConfig{
    {"Mainnet", kMainnetConfig},
    {"Frontier", test::kFrontierConfig},
    {"Homestead",
     {
         .chain_id = 1,
         .homestead_block = 0,
         .rule_set_config = protocol::EthashConfig{.validate_seal = false},
     }},
    {"FrontierToHomesteadAt5",
     {
         .chain_id = 1,
         .homestead_block = 5,
         .rule_set_config = protocol::EthashConfig{.validate_seal = false},
     }},
    {"HomesteadToDaoAt5",
     {
         .chain_id = 1,
         .homestead_block = 0,
         .dao_block = 5,
         .rule_set_config = protocol::EthashConfig{.validate_seal = false},
     }},
    {"EIP150",
     {
         .chain_id = 1,
         .homestead_block = 0,
         .tangerine_whistle_block = 0,
         .rule_set_config = protocol::EthashConfig{.validate_seal = false},
     }},
    // EEST tests@v20+ spelling of EIP150 (evmone #1576 followed the same rename).
    {"TangerineWhistle",
     {
         .chain_id = 1,
         .homestead_block = 0,
         .tangerine_whistle_block = 0,
         .rule_set_config = protocol::EthashConfig{.validate_seal = false},
     }},
    {"HomesteadToEIP150At5",
     {
         .chain_id = 1,
         .homestead_block = 0,
         .tangerine_whistle_block = 5,
         .rule_set_config = protocol::EthashConfig{.validate_seal = false},
     }},
    {"EIP158",
     {
         .chain_id = 1,
         .homestead_block = 0,
         .tangerine_whistle_block = 0,
         .spurious_dragon_block = 0,
         .rule_set_config = protocol::EthashConfig{.validate_seal = false},
     }},
    // EEST tests@v20+ spelling of EIP158.
    {"SpuriousDragon",
     {
         .chain_id = 1,
         .homestead_block = 0,
         .tangerine_whistle_block = 0,
         .spurious_dragon_block = 0,
         .rule_set_config = protocol::EthashConfig{.validate_seal = false},
     }},
    {"Byzantium",
     {
         .chain_id = 1,
         .homestead_block = 0,
         .tangerine_whistle_block = 0,
         .spurious_dragon_block = 0,
         .byzantium_block = 0,
         .rule_set_config = protocol::EthashConfig{.validate_seal = false},
     }},
    {"EIP158ToByzantiumAt5",
     {
         .chain_id = 1,
         .homestead_block = 0,
         .tangerine_whistle_block = 0,
         .spurious_dragon_block = 0,
         .byzantium_block = 5,
         .rule_set_config = protocol::EthashConfig{.validate_seal = false},
     }},
    {"Constantinople",
     {
         .chain_id = 1,
         .homestead_block = 0,
         .tangerine_whistle_block = 0,
         .spurious_dragon_block = 0,
         .byzantium_block = 0,
         .constantinople_block = 0,
         .rule_set_config = protocol::EthashConfig{.validate_seal = false},
     }},
    {"ConstantinopleFix",
     {
         .chain_id = 1,
         .homestead_block = 0,
         .tangerine_whistle_block = 0,
         .spurious_dragon_block = 0,
         .byzantium_block = 0,
         .constantinople_block = 0,
         .petersburg_block = 0,
         .rule_set_config = protocol::EthashConfig{.validate_seal = false},
     }},
    {"ByzantiumToConstantinopleFixAt5",
     {
         .chain_id = 1,
         .homestead_block = 0,
         .tangerine_whistle_block = 0,
         .spurious_dragon_block = 0,
         .byzantium_block = 0,
         .constantinople_block = 5,
         .petersburg_block = 5,
         .rule_set_config = protocol::EthashConfig{.validate_seal = false},
     }},
    {"Istanbul",
     {
         .chain_id = 1,
         .homestead_block = 0,
         .tangerine_whistle_block = 0,
         .spurious_dragon_block = 0,
         .byzantium_block = 0,
         .constantinople_block = 0,
         .petersburg_block = 0,
         .istanbul_block = 0,
         .rule_set_config = protocol::EthashConfig{.validate_seal = false},
     }},
    {"EIP2384",
     {
         .chain_id = 1,
         .homestead_block = 0,
         .tangerine_whistle_block = 0,
         .spurious_dragon_block = 0,
         .byzantium_block = 0,
         .constantinople_block = 0,
         .petersburg_block = 0,
         .istanbul_block = 0,
         .muir_glacier_block = 0,
         .rule_set_config = protocol::EthashConfig{.validate_seal = false},
     }},
    {"Berlin",
     {
         .chain_id = 1,
         .homestead_block = 0,
         .tangerine_whistle_block = 0,
         .spurious_dragon_block = 0,
         .byzantium_block = 0,
         .constantinople_block = 0,
         .petersburg_block = 0,
         .istanbul_block = 0,
         .muir_glacier_block = 0,
         .berlin_block = 0,
         .rule_set_config = protocol::EthashConfig{.validate_seal = false},
     }},
    {"London", test::kLondonConfig},
    {"BerlinToLondonAt5",
     {
         .chain_id = 1,
         .homestead_block = 0,
         .tangerine_whistle_block = 0,
         .spurious_dragon_block = 0,
         .byzantium_block = 0,
         .constantinople_block = 0,
         .petersburg_block = 0,
         .istanbul_block = 0,
         .muir_glacier_block = 0,
         .berlin_block = 0,
         .london_block = 5,
         .rule_set_config = protocol::EthashConfig{.validate_seal = false},
     }},
    {"ArrowGlacier",
     {
         .chain_id = 1,
         .homestead_block = 0,
         .tangerine_whistle_block = 0,
         .spurious_dragon_block = 0,
         .byzantium_block = 0,
         .constantinople_block = 0,
         .petersburg_block = 0,
         .istanbul_block = 0,
         .berlin_block = 0,
         .london_block = 0,
         .arrow_glacier_block = 0,
         .rule_set_config = protocol::EthashConfig{.validate_seal = false},
     }},
    {"GrayGlacier",
     {
         .chain_id = 1,
         .homestead_block = 0,
         .tangerine_whistle_block = 0,
         .spurious_dragon_block = 0,
         .byzantium_block = 0,
         .constantinople_block = 0,
         .petersburg_block = 0,
         .istanbul_block = 0,
         .berlin_block = 0,
         .london_block = 0,
         .gray_glacier_block = 0,
         .rule_set_config = protocol::EthashConfig{.validate_seal = false},
     }},
    {"Merge",
     {
         .chain_id = 1,
         .homestead_block = 0,
         .tangerine_whistle_block = 0,
         .spurious_dragon_block = 0,
         .byzantium_block = 0,
         .constantinople_block = 0,
         .petersburg_block = 0,
         .istanbul_block = 0,
         .berlin_block = 0,
         .london_block = 0,
         .terminal_total_difficulty = 0,
     }},
    {"Paris",  // same as Merge
     {
         .chain_id = 1,
         .homestead_block = 0,
         .tangerine_whistle_block = 0,
         .spurious_dragon_block = 0,
         .byzantium_block = 0,
         .constantinople_block = 0,
         .petersburg_block = 0,
         .istanbul_block = 0,
         .berlin_block = 0,
         .london_block = 0,
         .terminal_total_difficulty = 0,
     }},
    {"ArrowGlacierToMergeAtDiffC0000",
     {
         .chain_id = 1,
         .homestead_block = 0,
         .tangerine_whistle_block = 0,
         .spurious_dragon_block = 0,
         .byzantium_block = 0,
         .constantinople_block = 0,
         .petersburg_block = 0,
         .istanbul_block = 0,
         .berlin_block = 0,
         .london_block = 0,
         .arrow_glacier_block = 0,
         .terminal_total_difficulty = 0xC0000,
         .rule_set_config = protocol::EthashConfig{.validate_seal = false},
     }},
    {"ArrowGlacierToParisAtDiffC0000",
     {
         .chain_id = 1,
         .homestead_block = 0,
         .tangerine_whistle_block = 0,
         .spurious_dragon_block = 0,
         .byzantium_block = 0,
         .constantinople_block = 0,
         .petersburg_block = 0,
         .istanbul_block = 0,
         .berlin_block = 0,
         .london_block = 0,
         .arrow_glacier_block = 0,
         .terminal_total_difficulty = 0xC0000,
         .rule_set_config = protocol::EthashConfig{.validate_seal = false},
     }},
    {"Shanghai", test::kShanghaiConfig},
    {"MergeToShanghaiAtTime15k",
     {
         .chain_id = 1,
         .homestead_block = 0,
         .tangerine_whistle_block = 0,
         .spurious_dragon_block = 0,
         .byzantium_block = 0,
         .constantinople_block = 0,
         .petersburg_block = 0,
         .istanbul_block = 0,
         .berlin_block = 0,
         .london_block = 0,
         .terminal_total_difficulty = 0,
         .shanghai_time = 15'000,
     }},
    {"ParisToShanghaiAtTime15k",
     {
         .chain_id = 1,
         .homestead_block = 0,
         .tangerine_whistle_block = 0,
         .spurious_dragon_block = 0,
         .byzantium_block = 0,
         .constantinople_block = 0,
         .petersburg_block = 0,
         .istanbul_block = 0,
         .berlin_block = 0,
         .london_block = 0,
         .terminal_total_difficulty = 0,
         .shanghai_time = 15'000,
     }},
    {"Cancun",
     {
         .chain_id = 1,
         .homestead_block = 0,
         .tangerine_whistle_block = 0,
         .spurious_dragon_block = 0,
         .byzantium_block = 0,
         .constantinople_block = 0,
         .petersburg_block = 0,
         .istanbul_block = 0,
         .berlin_block = 0,
         .london_block = 0,
         .terminal_total_difficulty = 0,
         .shanghai_time = 0,
         .cancun_time = 0,
     }},
    {"ShanghaiToCancunAtTime15k",
     {
         .chain_id = 1,
         .homestead_block = 0,
         .tangerine_whistle_block = 0,
         .spurious_dragon_block = 0,
         .byzantium_block = 0,
         .constantinople_block = 0,
         .petersburg_block = 0,
         .istanbul_block = 0,
         .berlin_block = 0,
         .london_block = 0,
         .terminal_total_difficulty = 0,
         .shanghai_time = 0,
         .cancun_time = 15'000,
     }},
    {"Prague",
     {
         .chain_id = 1,
         .homestead_block = 0,
         .tangerine_whistle_block = 0,
         .spurious_dragon_block = 0,
         .byzantium_block = 0,
         .constantinople_block = 0,
         .petersburg_block = 0,
         .istanbul_block = 0,
         .berlin_block = 0,
         .london_block = 0,
         .terminal_total_difficulty = 0,
         .shanghai_time = 0,
         .cancun_time = 0,
         .prague_time = 0,
     }},
    {"CancunToPragueAtTime15k",
     {
         .chain_id = 1,
         .homestead_block = 0,
         .tangerine_whistle_block = 0,
         .spurious_dragon_block = 0,
         .byzantium_block = 0,
         .constantinople_block = 0,
         .petersburg_block = 0,
         .istanbul_block = 0,
         .berlin_block = 0,
         .london_block = 0,
         .terminal_total_difficulty = 0,
         .shanghai_time = 0,
         .cancun_time = 0,
         .prague_time = 15'000,
     }},
    {"Osaka",
     {
         .chain_id = 1,
         .homestead_block = 0,
         .tangerine_whistle_block = 0,
         .spurious_dragon_block = 0,
         .byzantium_block = 0,
         .constantinople_block = 0,
         .petersburg_block = 0,
         .istanbul_block = 0,
         .berlin_block = 0,
         .london_block = 0,
         .terminal_total_difficulty = 0,
         .shanghai_time = 0,
         .cancun_time = 0,
         .prague_time = 0,
         .osaka_time = 0,
     }},
    {"Amsterdam",
     {
         .chain_id = 1,
         .homestead_block = 0,
         .tangerine_whistle_block = 0,
         .spurious_dragon_block = 0,
         .byzantium_block = 0,
         .constantinople_block = 0,
         .petersburg_block = 0,
         .istanbul_block = 0,
         .berlin_block = 0,
         .london_block = 0,
         .terminal_total_difficulty = 0,
         .shanghai_time = 0,
         .cancun_time = 0,
         .prague_time = 0,
         .osaka_time = 0,
         .amsterdam_time = 0,
     }},
    {"PragueToOsakaAtTime15k",
     {
         .chain_id = 1,
         .homestead_block = 0,
         .tangerine_whistle_block = 0,
         .spurious_dragon_block = 0,
         .byzantium_block = 0,
         .constantinople_block = 0,
         .petersburg_block = 0,
         .istanbul_block = 0,
         .berlin_block = 0,
         .london_block = 0,
         .terminal_total_difficulty = 0,
         .shanghai_time = 0,
         .cancun_time = 0,
         .prague_time = 0,
         .osaka_time = 15'000,
     }},
    {"OsakaToBPO1AtTime15k",
     {
         .chain_id = 1,
         .homestead_block = 0,
         .tangerine_whistle_block = 0,
         .spurious_dragon_block = 0,
         .byzantium_block = 0,
         .constantinople_block = 0,
         .petersburg_block = 0,
         .istanbul_block = 0,
         .berlin_block = 0,
         .london_block = 0,
         .terminal_total_difficulty = 0,
         .shanghai_time = 0,
         .cancun_time = 0,
         .prague_time = 0,
         .osaka_time = 0,
         .bpo1_time = 15'000,
     }},
    {"BPO1ToBPO2AtTime15k",
     {
         .chain_id = 1,
         .homestead_block = 0,
         .tangerine_whistle_block = 0,
         .spurious_dragon_block = 0,
         .byzantium_block = 0,
         .constantinople_block = 0,
         .petersburg_block = 0,
         .istanbul_block = 0,
         .berlin_block = 0,
         .london_block = 0,
         .terminal_total_difficulty = 0,
         .shanghai_time = 0,
         .cancun_time = 0,
         .prague_time = 0,
         .osaka_time = 0,
         .bpo1_time = 0,
         .bpo2_time = 15'000,
     }},
    {"BPO2ToBPO3AtTime15k",
     {
         .chain_id = 1,
         .homestead_block = 0,
         .tangerine_whistle_block = 0,
         .spurious_dragon_block = 0,
         .byzantium_block = 0,
         .constantinople_block = 0,
         .petersburg_block = 0,
         .istanbul_block = 0,
         .berlin_block = 0,
         .london_block = 0,
         .terminal_total_difficulty = 0,
         .shanghai_time = 0,
         .cancun_time = 0,
         .prague_time = 0,
         .osaka_time = 0,
         .bpo1_time = 0,
         .bpo2_time = 0,
         .bpo3_time = 15'000,
     }},
    {"BPO3ToBPO4AtTime15k",
     {
         .chain_id = 1,
         .homestead_block = 0,
         .tangerine_whistle_block = 0,
         .spurious_dragon_block = 0,
         .byzantium_block = 0,
         .constantinople_block = 0,
         .petersburg_block = 0,
         .istanbul_block = 0,
         .berlin_block = 0,
         .london_block = 0,
         .terminal_total_difficulty = 0,
         .shanghai_time = 0,
         .cancun_time = 0,
         .prague_time = 0,
         .osaka_time = 0,
         .bpo1_time = 0,
         .bpo2_time = 0,
         .bpo3_time = 0,
         .bpo4_time = 15'000,
     }},
    {"BPO2ToAmsterdamAtTime15k",
     {
         .chain_id = 1,
         .homestead_block = 0,
         .tangerine_whistle_block = 0,
         .spurious_dragon_block = 0,
         .byzantium_block = 0,
         .constantinople_block = 0,
         .petersburg_block = 0,
         .istanbul_block = 0,
         .berlin_block = 0,
         .london_block = 0,
         .terminal_total_difficulty = 0,
         .shanghai_time = 0,
         .cancun_time = 0,
         .prague_time = 0,
         .osaka_time = 0,
         .bpo1_time = 0,
         .bpo2_time = 0,
         .amsterdam_time = 15'000,
     }},
    // Hardcoded glamsterdam-devnet-7 chain config (devnet-specific: a new devnet needs its own entry).
    // The MFBD input carries only the network name; the guest maps it here to chain_id + blob schedule
    // (via bpo/amsterdam fork times) + fork activation. amsterdam_time=0 => revision() returns EVMC_AMSTERDAM.
    {"glamsterdam-devnet-7",
     {
         .chain_id = 0x1a62c8cb6,
         .homestead_block = 0,
         .tangerine_whistle_block = 0,
         .spurious_dragon_block = 0,
         .byzantium_block = 0,
         .constantinople_block = 0,
         .petersburg_block = 0,
         .istanbul_block = 0,
         .berlin_block = 0,
         .london_block = 0,
         .terminal_total_difficulty = 0,
         .shanghai_time = 0,
         .cancun_time = 0,
         .prague_time = 0,
         .osaka_time = 0,
         .bpo1_time = 0,
         .bpo2_time = 0,
         .amsterdam_time = 0,
     }},
    // Hardcoded glamsterdam-devnet-8 chain config (devnet-specific: a new devnet needs its own entry).
    {"glamsterdam-devnet-8",
     {
         .chain_id = 0x1a6a8cc6e,
         .homestead_block = 0,
         .tangerine_whistle_block = 0,
         .spurious_dragon_block = 0,
         .byzantium_block = 0,
         .constantinople_block = 0,
         .petersburg_block = 0,
         .istanbul_block = 0,
         .berlin_block = 0,
         .london_block = 0,
         .terminal_total_difficulty = 0,
         .shanghai_time = 0,
         .cancun_time = 0,
         .prague_time = 0,
         .osaka_time = 0,
         .bpo1_time = 0,
         .bpo2_time = 0,
         .amsterdam_time = 0,
     }},
    // Sepolia fork times (kSepoliaConfig) with the pre-merge forks at genesis: stateless
    // validation of post-merge blocks has no total difficulty for the TTD rule set.
    {"sepolia",
     {
         .chain_id = 11155111,
         .homestead_block = 0,
         .tangerine_whistle_block = 0,
         .spurious_dragon_block = 0,
         .byzantium_block = 0,
         .constantinople_block = 0,
         .petersburg_block = 0,
         .istanbul_block = 0,
         .berlin_block = 0,
         .london_block = 0,
         .terminal_total_difficulty = 0,
         .shanghai_time = 1677557088,
         .cancun_time = 1706655072,
         .prague_time = 1741159776,
         .osaka_time = 1760427360,
         .bpo1_time = 1761017184,
         .bpo2_time = 1761607008,
         .amsterdam_time = 1791294816,
     }},
};

std::vector<Transaction> sample_transactions();
std::vector<Receipt> sample_receipts();

}  // namespace silkworm::test
